feat: create symlink operator
treeverse/airflow-provider-lakeFS pull request #41
Opened 2022-12-22 10:38 UTC by rinzool

## Why
See: https://github.com/treeverse/airflow-provider-lakeFS/issues/40 

## How
* Update hook to add a `create_symlink_file` method
* Create a `CreateSymlinkOperator` which takes a repo and a branch and creates a symlink file

2022-12-22 17:07 UTC, Jonathan-Rosenberg requested changes
Very cool, thank you for that @rinzool!

Would you mind adding the optional [`location` parameter](https://pydocs.lakefs.io/docs/MetadataApi.html#create_symlink_file)?
https://docs.lakefs.io/reference/api.html#/metadata/createSymlinkFile

2022-12-22 23:02 UTC, rinzool commented
> Very cool, thank you for that @rinzool!
> 
> Would you mind adding the optional [`location` parameter](https://pydocs.lakefs.io/docs/MetadataApi.html#create_symlink_file)? https://docs.lakefs.io/reference/api.html#/metadata/createSymlinkFile

Done! Thank you I didn't notice that `location` was an optional parameter of the route

Furthermore, I was considering defining a default value for `lakefs_conn_id` like `lakefs_conn_id = "conn_lakefs"` (like other providers such as databricks or airflow which define default value for conn id)
But it is not the case for other operators in this provider so I wasn't sure

2022-12-26 11:59 UTC, Jonathan-Rosenberg commented on lakefs_provider/hooks/lakefs_hook.py
> +    def create_symlink_file(self, repo: str, branch: str)  -> str:
Where do you address the optional `location` property?

2022-12-26 11:59 UTC, Jonathan-Rosenberg commented on lakefs_provider/operators/create_symlink_operator.py
> +        location: str = None,
You don't set it anywhere...

2022-12-26 12:00 UTC, Jonathan-Rosenberg commented on lakefs_provider/operators/create_symlink_operator.py
> +        location = hook.create_symlink_file(self.repo, self.branch, **api_kwargs)
Please use a different name for the location so it will reflect the storage URI location and not the optional param.

2022-12-26 12:07 UTC, Jonathan-Rosenberg requested changes
Thanks!
Just a few comments in the files themselves...
Regarding `lakefs_conn_id`, sounds like a good idea yet not in the context of this PR. This will also imply updating the documentation.

2022-12-28 09:04 UTC, rinzool commented
Sorry @Jonathan-Rosenberg, now it should be all good!

2022-12-28 21:57 UTC, lukland reviewed
Hello, I was passing by and saw a few things to fix.

2022-12-28 21:57 UTC, lukland commented on lakefs_provider/operators/create_symlink_operator.py
> +    Create a symlnik file
```suggestion
    Create a symlink file
```

2022-12-28 21:57 UTC, lukland commented on lakefs_provider/operators/create_symlink_operator.py
> +
```suggestion
```
In order to be [PEP8 compliant](https://peps.python.org/pep-0008/#imports)

2022-12-29 19:08 UTC, arielshaqed commented
Hi @rinzool ,

Thanks for the PR. Really excited to see serious usage increasing! 🥳 

One tricky thing: It should eventually have tests. :slightly_smiling_face: Otherwise things break.

The most important thing would be a description (in a comment on the PR) about how you checked this.

@itaiad200  did some stuff based on how Astronomer write tests, so [this bit](https://github.com/treeverse/airflow-provider-lakeFS/blob/0cd7151a800628a228eb9762bdaae607e687126a/.github/workflows/provider.yaml#L59-L65) runs them and [this is the entrypoint](https://github.com/treeverse/airflow-provider-lakeFS/blob/0cd7151a800628a228eb9762bdaae607e687126a/lakefs_provider/example_dags/lakefs-dag.py#L75) to the test.  If it's too difficult, let's pull and I can probably add a test myself. But I would need a description of the manual test you performed: setup, the DAG you ran, the result.  I would like the test to be able verify that we don't break your use case!

Thanks again!

2022-12-30 09:38 UTC, rinzool commented
Thanks @arielshaqed 
I updated `lakefs-dag.py` to add the operator on `example-branch` and I updated `Provider` workflow so it checks that symlink file exists and verifies that it has one line containing `local://`

I executed all workflow commands locally and it works fine (the DAG has the new operator, and I can see the symlink). Can you please approve the workflow please? :pray: Note that the [previous run](https://github.com/treeverse/airflow-provider-lakeFS/actions/runs/3799287216/jobs/6468120674) failed with a 403 when running command
```AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY aws s3 cp --endpoint-url=http://s3.local.lakefs.io:8000/ s3://example-repo/main/path/to/_SUCCESS -```
I don't really understand why (it seems not related to my PR but I'm not sure) :thinking:

2022-12-30 10:14 UTC, rinzool commented
@arielshaqed And about testing, while developing this feature, I was thinking about adding some simple unit tests with pytest (or unittest) to validate that my provider calls the good hook method with appropriate arguments, etc. But I did not feel legitimate to add unit tests with a workflow on a repository that I do not own

But I just commited a _pytest_ workflow and a unit test files for my new operator. If necessary I will drop the commit :wink:

2023-01-02 07:48 UTC, arielshaqed commented
Hi @rinzool!

First of all, thanks so much for adding tests -- it makes it much easier to understand the intent of the code, and even more importantly it will allow us to ensure that your contribution continues to work with as lakeFS (and even Amazonian S3 deployments...) change!

I see we are running into problems getting the **unit test** to work.  These problems are not related to code quality, rather there is some issue (that I do not understand...) with Airflow and/or Python and/or GitHub actions and/or something else integration.  I do not want to block on getting the unit test to work: it tests that your code works in isolation, when in fact the bad failure modes I can imagine are in integration (incompatibility with the lakeFS API, bad composability in Airflow, ...).

I do not want to block this PR on the unit test - please feel very free to remove it entirely.

On the other hand, for precisely these reasons I want us to get the integration test to pass!  Unfortunately that means that I cannot approve until does.

I will work with you until it passes; this may end up with some small fixes of mine, so I'd be happy to know you won't mind me pushing here.

2023-01-02 08:54 UTC, rinzool commented
Thanks @arielshaqed for helping me, please feel free to push on this branch! I managed to fix the unit test workflow: there was an issue when installing requirements:
```
[launchpadlib 1.10.6 requires testresources which is not installed](https://gist.github.com/y56/0540d22a1db40dacc7fbbb93c866821e)``` (issue described [here](https://gist.github.com/y56/0540d22a1db40dacc7fbbb93c866821e))
I fixed it by using the latest ubuntu runner.
I hoped that it would fix the _Provider_ workflow but unfortunately not :confused:

2023-01-02 09:00 UTC, arielshaqed commented
I believe the integration ("provider") test will start working once #43 is done, and then we'll pull this.

2023-01-02 09:20 UTC, arielshaqed commented
@rinzool could you rebase on main (now with #43)?  I believe that will allow the integration test at least to _start_.

@Jonathan-Rosenberg did a much more in-depth review of the code and still has changes marked requested.

2023-01-02 09:29 UTC, Jonathan-Rosenberg approved these changes
LGTM
Thanks @rinzool !

2023-01-02 10:22 UTC, arielshaqed commented
Tests pass, neat!  Thanks for bearing with us for this, and see you on the lake!

2023-01-02 10:22 UTC, merged